name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{matrix.platform}}
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.16.x
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Lint
        uses: magefile/mage-action@v2
        with:
          version: latest
          args: lint
      - name: Doc Verify
        uses: magefile/mage-action@v2
        with:
          version: latest
          args: docVerify
      - name: Test
        uses: magefile/mage-action@v2
        with:
          version: latest
          args: test
